{
  dataset_group: "ADMET",
  dataset: "cyp2d6_veith",
  task_type: "classification",
  num_tasks: 1,
  scaler: False,
  log_scaler: False,
  weight_loss: True,
  metric: "auprc",
  pretrain_model: "ChemFM/ChemFM-3B",
  tokenizer_path: "tokenizer",
  optim: "adamw_torch",
  weight_decay: 0.1,
  lr_scheduler_type: "cosine_with_min_lr",
  learning_rate: 2.0e-5,
  min_learning_rate: 2.0e-6,
  num_train_epochs: 20,
  warmup_ratio: 0.05,
  attention_dropout: 0.2,
  lora: True,
  lora_rank: 16,
  lora_alpha_ratio: 1.0,
  lora_dropout: 0.6,
  per_device_train_batch_size: 8,
  gradient_accumulation_steps: 2,
  molecule_source_aug_prob: 1.0,
  num_data_seeds: 1,
  seed: 533,
  output_dir: "./outputs/admet_combine/cyp2d6_veith",
  adapter_name: "admet_cyp2d6_veith",
  combine_train_val_test: True
}