{
  dataset_group: "ADMET",
  dataset: "hia_hou",
  task_type: "classification",
  num_tasks: 1,
  scaler: False,
  log_scaler: False,
  weight_loss: True,
  metric: "auroc",
  pretrain_model: "ChemFM/ChemFM-3B",
  tokenizer_path: "tokenizer",
  optim: "adamw_torch",
  weight_decay: 0.07,
  lr_scheduler_type: "cosine_with_min_lr",
  learning_rate: 8.0e-4,
  min_learning_rate: 8.0e-5,
  num_train_epochs: 20,
  warmup_ratio: 0.13,
  attention_dropout: 0.2,
  lora: True,
  lora_rank: 8,
  lora_alpha_ratio: 1.0,
  lora_dropout: 0.6,
  per_device_train_batch_size: 8,
  gradient_accumulation_steps: 2,
  molecule_source_aug_prob: 0.8,
  num_data_seeds: 1,
  seed: 533,
  output_dir: "./outputs/admet_combine/hia_hou",
  adapter_name: "admet_hia_hou",
  combine_train_val_test: True
}