{
  dataset_group: "ADMET",
  dataset: "lipophilicity_astrazeneca",
  task_type: "regression",
  num_tasks: 1,
  scaler: True,
  log_scaler: False,
  weight_loss: False,
  metric: "mae",
  pretrain_model: "ChemFM/ChemFM-3B",
  tokenizer_path: "tokenizer",
  optim: "adamw_torch",
  weight_decay: 0.1,
  lr_scheduler_type: "cosine_with_min_lr",
  learning_rate: 2.0e-4,
  min_learning_rate: 2.0e-5,
  num_train_epochs: 20,
  warmup_ratio: 0.05,
  attention_dropout: 0.0,
  lora: True,
  lora_rank: 8,
  lora_alpha_ratio: 1.0,
  lora_dropout: 0.6,
  per_device_train_batch_size: 8,
  gradient_accumulation_steps: 1,
  molecule_source_aug_prob: 1.0,
  num_data_seeds: 1,
  seed: 533,
  output_dir: "./outputs/admet_combine/lipophilicity_astrazeneca",
  adapter_name: "admet_lipophilicity_astrazeneca",
  combine_train_val_test: True
}