{
  dataset: "USPTO-MIT-Retro",
  pretrain_model: "ChemFM/ChemFM-3B",
  tokenizer_path: "tokenizer",
  seed: 533,
  lora: True,
  lora_model_path: "outputs/USPTO-MIT-Retro/checkpoint/USPTO-MIT-Retro",
  original_data_augmentations: 5
}