{
  dataset: "USPTO-MIT-Retro",
  pretrain_model: "ChemFM/ChemFM-3B",
  tokenizer_path: "tokenizer",
  optim: "adamw_torch",
  weight_decay: 0.01,
  lr_scheduler_type: "cosine_with_min_lr",
  learning_rate: 1.0e-4,
  min_learning_rate: 1.0e-5,
  num_train_epochs: 10,
  warmup_ratio: 0.05,
  attention_dropout: 0.1,
  lora: True,
  lora_rank: 64,
  lora_alpha_ratio: 1.0,
  lora_dropout: 0.1,
  per_device_train_batch_size: 4,
  gradient_accumulation_steps: 2,
  seed: 533,
  output_dir: "./outputs/USPTO-MIT-Retro",
  max_test_samples: 2000
}