{
  dataset_group: "ADMET",
  dataset: "cyp3a4_substrate_carbonmangles",
  task_type: "classification",
  num_tasks: 1,
  scaler: False,
  log_scaler: False,
  weight_loss: True,
  metric: "auroc",
  pretrain_model: "ChemFM/ChemFM-3B",
  tokenizer_path: "tokenizer",
  optim: "adamw_torch",
  weight_decay: 0.05,
  lr_scheduler_type: "cosine_with_min_lr",
  learning_rate: 8.0e-5,
  min_learning_rate: 8.0e-6,
  num_train_epochs: 20,
  early_stopping_patience: 10,
  early_stopping_start_epoch: 100,
  warmup_ratio: 0.05,
  attention_dropout: 0.4,
  lora: True,
  lora_rank: 32,
  lora_alpha_ratio: 1.0,
  lora_dropout: 0.4,
  per_device_train_batch_size: 8,
  gradient_accumulation_steps: 2,
  molecule_source_aug_prob: 1.0,
  num_data_seeds: 5,
  seed: 533,
  output_dir: "./outputs/admet/cyp3a4_substrate_carbonmangles",
}