{
  dataset: "guacamol",
  has_scaffold: False,
  scaffold_aug_prob: 0.0,
  molecule_target_aug_prob: 1.0,
  pretrain_model: "ChemFM/ChemFM-3B",
  tokenizer_path: "tokenizer",
  optim: "adamw_torch",
  weight_decay: 0.01,
  warmup_ratio: 0.01,
  lr_scheduler_type: "cosine_with_min_lr",
  learning_rate: 6.0e-4,
  min_learning_rate: 6.0e-5,
  num_train_epochs: 10,
  lora: False,
  per_device_train_batch_size: 12,
  per_device_eval_batch_size: 128,
  gradient_accumulation_steps: 4,
  seed: 0,
  output_dir: "./outputs/guacamol",
  save_strategy: "epoch",
  evaluation_strategy: "epoch",
  ddp_find_unused_parameters: False
}