{
  dataset_group: "ADMET",
  dataset: "hia_hou",
  task_type: "classification",
  num_tasks: 1,
  scaler: False,
  log_scaler: False,
  weight_loss: True,
  metric: "auroc",
  pretrain_model: "ChemFM/ChemFM-1B",
  tokenizer_path: "tokenizer",
  optim: "adamw_torch",
  weight_decay: 0.01,
  lr_scheduler_type: "cosine_with_min_lr",
  learning_rate: 2.0e-4,
  min_learning_rate: 2.0e-5,
  num_train_epochs: 50,
  warmup_ratio: 0.05,
  attention_dropout: 0.2,
  lora: True,
  lora_rank: 2,
  lora_alpha_ratio: 1.0,
  lora_dropout: 0.4,
  per_device_train_batch_size: 8,
  gradient_accumulation_steps: 1,
  molecule_source_aug_prob: 1.0,
  num_data_seeds: 5,
  seed: 533,
  output_dir: "./outputs/admet/hia_hou"
}