{
  dataset: "USPTO-FULL-Retro",
  pretrain_model: "ChemFM/ChemFM-3B",
  tokenizer_path: "tokenizer",
  seed: 533,
  lora: True,
  model_path: "outputs/USPTO-FULL-Retro/checkpoint/USPTO-FULL-Retro",
  original_data_augmentations: 5
}