{
  dataset: "USPTO-50K-Retro",
  pretrain_model: "ChemFM/ChemFM-3B",
  tokenizer_path: "tokenizer",
  seed: 533,
  lora: True,
  model_path: "outputs/USPTO-50K-Retro/checkpoint/USPTO-50K-Retro",
  original_data_augmentations: 20
}